@startuml diagrama_componentes
skinparam packageStyle rectangle
skinparam shadowing true
skinparam linetype ortho
skinparam defaultFontName Arial
skinparam defaultFontSize 12

package "Análise Léxica" #LightBlue {
    [Lexer] as lexer
    [Token] as token
	[Valor] as valor
    [Erro Léxico] as erro_lexico
}

package "Análise Sintática" #LightGreen {
    [Parser] as parser
    [Expressão] as expressao
    [Instrução] as instrucao
    [Erro Sintático] as erro_sintatico
    interface Chumsky as chumsky
}

package "Interpretação" #LightYellow {
    [Interpretador] as interpretador
    [Executador] as executador
    [Avaliador] as avaliador
    [Erro de Tempo de Execução] as erro_execucao
    interface Flecs as flecs
}

interface Thiserror as thiserror

lexer ..> token
lexer ..> erro_lexico
token -> valor
erro_lexico ..|> thiserror

parser ..> expressao
parser ..> instrucao
parser ..> erro_sintatico
parser ..> chumsky
instrucao -> expressao
expressao -d-> valor
erro_sintatico ..|> thiserror

interpretador ..> executador
interpretador ..> instrucao
interpretador ..> erro_execucao
avaliador .> valor
avaliador .d.> expressao
avaliador .> flecs
executador ..> avaliador
executador .> valor
executador .d.> instrucao
executador .> flecs
erro_execucao ..|> thiserror

@enduml
